# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714b6b848e5ca3f2c45ac97470cdb7938ed9c7aa16e6cbfff4da6591e150aee02322bbd3854bace5ae87aacaf26c39a932499f78a4abf7e97a4f14289f9b644b

test:
  secret_key_base: 9bd6a5a2fa04f67dddd549e49b19d6ee55a4515e8684db0c4f9a47970f6c01fcb642a8b1033347f0038632612f86420777e0aeccd597000a085a5f7628703a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
